### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by Thorski** [edelstone/material-palette-generator#3]
I just have a question.

I am wondering if the algorithm or original source code is documented anywhere?

In particular, the given primary color is not in the 'center' of the palette, I am wondering how it chooses the place for the given color.   For instance a light color might be assigned to '100' and mostly darker colors generated, but a darker color might be assigned to '700' or '800' and mostly lighter colors generated.  

Thank you.

-- Thor

**Comment by edelstone** [comment]
Hi @Thorski, that's the big downside to this repo. The only thing I was trying to do with this project was to make Google's version that is buried in their docs easier to find in a web search. Unfortunately it uses the obfuscated code.

I'm not aware of any place the algorithm or original source code is published

**Comment by max-hk** [comment]
> Hi @Thorski, that's the big downside to this repo. The only thing I was trying to do with this project was to make Google's version that is buried in their docs easier to find in a web search. Unfortunately it uses the obfuscated code.
> 
> I'm not aware of any place the algorithm or original source code is published

There are several attempts to reverse engineer the algorithm, like [eugeneford/material-palette-generator](https://github.com/eugeneford/material-palette-generator/blob/master/src/index.js#L798) and [wszgrcy/material-color-palettes-generator (with Chinese comments)](https://github.com/wszgrcy/material-color-palettes-generator).

Hope it helps.

**Comment by edelstone** [comment]
Interesting. Thanks @maxloh.
