### ISSUE TITLE
Suggestion: Export palette

### ISSUE THREAD

**Issue by AlanAcDz** [edelstone/material-palette-generator#4]
Hi, I just found this tool and I think it's pretty good. 
May I suggest having the option to view or download the generated palette as CSS or Sass variables. 
As a developer, I think this would make the tool a lot more useful than the default Google one.

**Comment by edelstone** [comment]
@AlanAcDz Thanks for the suggestion. I like the idea; would be a good way to start differentiating this product from the hidden Google one.

This is beyond my capabilities but I’ll leave the issue open so we can try to solicit help. Many thanks.

**Comment by edelstone** [comment]
@AlanAcDz Does JSON export solve your particular issue?
