### ISSUE TITLE
Export modal is open by default on mobile devices

### ISSUE THREAD

**Issue by edelstone** [edelstone/material-palette-generator#6]
On my iPhone using Safari, the export modal is open when the page loads. Additionally the dialog is empty, and cannot be closed. This makes the site unusable on the iPhone and maybe other mobile devices.

@ziyafenn Take a look at this and let me know if you can fix. I may have to roll back #5 if not. My apologies for not checking before merging this.

![IMG_521751D7D90F-1](https://user-images.githubusercontent.com/8269046/90387822-7a2b0f00-e04c-11ea-83fb-350a1fbd086b.jpeg)

**Comment by ziyafenn** [comment]
@edelstone i'll take a look tonight. I'm working now on a sketch plugin that can use the exported JSON to create a color palette inside Sketch. I'll create an issue for that too :)

**Comment by edelstone** [comment]
If the tabindex stuff you did on that last commit in #5 is causing the problem, just revert it and I'll make a new issue to investigate tabbing accessibility across the entire app. That's probably a better strategy.
