### ISSUE TITLE
Add a link to sketch plugin for importing JSON

### ISSUE THREAD

**Issue by ziyafenn** [edelstone/material-palette-generator#8]
hey @edelstone ,

i've created a plugin for Sketch that works out-of-box with the exported JSON from materialpalettes.

Would be nice if you could link it here on readme.

Here is the link https://github.com/ziyafenn/sketch-json-color-palette-importer

PS.

Material Theme Editor plugin [has been retired](https://material.io/tools/theme-editor/).

**Comment by edelstone** [comment]
Will do.  And yeah, I noticed Material Theme Editor had been retired. I continue linking to it since they explain why and link to other resources. Thanks for this!
